config/routes.rb
Rails.application.routes.draw do

match '*path', :controller => 'application', :action => 'handle_options_request', via: :options
  root  to: 'searches#home'
  get 'results', to: 'searches#search'
  get 'makers/index'
  get 'searches/getfacets', to: 'searches#getfacets'

  get 'retailers/allocate'
  get 'retailers', to: 'retailers#index' 
  patch 'retailers/:id/linktomaker', to: 'retailers#linktomaker', as: 'linkto'

  resources :makers
  resources :retailers
require 'resque/server'
require 'resque-scheduler'
require 'resque/scheduler/server'

mount Resque::Server, at: '/jobs'  


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/maker.rb
class Maker < ApplicationRecord
	has_many :retailers, :inverse_of => :maker

	def to_hash
		{id: id, brand: brand,code: code, kind: kind, size: size, series: series, model: model}
	end #to_hash	

end#class Meker

app/models/merchant.rb
class Merchant < ApplicationRecord
end

app/models/retailer.rb
class Retailer < ApplicationRecord
	include Solr
  	belongs_to :maker, :inverse_of => :retailers
  	belongs_to :merchant, foreign_key: 'shop', primary_key: 'code'

        scope :active, -> { where(active: true) }

        #send selected retailers to Solr module for matchig
        #res: refers to whether to include all retailer in response
        #rec:  refers to whether to include all retailer in Solr match

	def self.alloc(merchant,res=nil,rec=nil,count=50,offset=nil)
		@rsp =  if(rec == 'all') 
				Solr.match(Retailer.where(shop: merchant).limit(count))
			else	
				Solr.match(Retailer.where(shop: merchant, maker_id: 3604).limit(count).offset(offset))
			end #if	
			
		@rsp.each do |k,v|
			if v.length == 1 || (!v.empty? && v[0]['score'] - v[1]['score'] > 2.2)
			Maker.find(v[0]["id"]).retailers << k
			@rsp.delete(k) unless res == "all"
			end#if
		end	#rsp.each
		log_allocate(@rsp) 
		@rsp 
	end #allocate   

	def self.csv_import file
		log_file = File.new("#{Rails.root}/log/Retailer_Update_log.txt","w")
		File.open(log_file,"a+")
			CSV.foreach(file, headers: true, :quote_char => '\'',:col_sep => '~') do |row|
				begin 
				retailer =  check_for_retailer(row.field('title'), row.field('link'))
					if retailer 
          retailer.update(active: true)
					retailer.check_price(row.field('price').to_i)
					else
					tmp_retailer = row.to_h
					puts tmp_retailer
                                        tmp_retailer["shop"] = tmp_retailer["merchant"]
					tmp_retailer.delete("merchant")
					puts Retailer.create!(tmp_retailer)
					end #if retailer
				rescue  StandardError => e
				puts e	
				b = binding
				log_file << "[#{File.basename(file,'.csv').upcase}]: [UPDATE]: ROW IN ERROR =>\n"	
				log_file <<  b.eval("row") 
				log_file << "[ERROR MESSAGE]: #{e.message}\n\n"
				end # rescue	
			end # CSV.foreach
		log_file.flush.close
	end #csv_import	

	def check_price new_price
		new_price != price ? update(price: new_price) : touch
	end #check_price

	# Deactivate retailers if their last updated time is before a given timestamp
	def self.deactivate_records merchant,time
		Retailer.where("shop  = ? AND updated_at < ?",merchant,time).each {|retailer| retailer.update(active: false)}
	end	# deactivate_records

	def to_log
		id.to_s + "\t" + title + "\t" + "\t\tACTIVE:\t" +active.to_s
	end #to_log

	# Delete records if they have been inactive in the last 15 days
	def self.clean_old_records time
		Retailer.where("active = ? AND updated_at < ?",false,time).each {|retailer| retailer.destroy}
	end	# clean_old_records

	def to_log
		id.to_s + "\t" + title + "\t" + "\t\tACTIVE:\t" +active.to_s
	end #to_log
	
	private

	def self.check_for_retailer title,link
		result = Retailer.where(title: title, link: link)
		result.length == 1 ? result.first : false
	end	# check_for_retailer

	def find_maker(hash) 
		Maker.find_by!(hash)
		rescue ActiveRecord::RecordNotFound
		raise NoMatchError.new(hash)
	end	

	def find_makers(hash,n=3) 
		Maker.where(hash).take(n)
	end	


	def self.log_allocate(match_hash)
		match_hash.each do |k,v|
			Solr::MATCH_LOG_FILE.puts("______________________________________________________________________________")
			Solr::MATCH_LOG_FILE.puts(k.to_log)
			Solr::MATCH_LOG_FILE.puts("..............................................................................")
			v.empty? ? Solr::MATCH_LOG_FILE.puts("..NO MATCH FOUND!...") : log_matches(v)
			Solr::MATCH_LOG_FILE.puts("______________________________________________________________________________")
			Solr::MATCH_LOG_FILE.puts
		end #match_hash.each

		Solr::MATCH_LOG_FILE.flush
	end #log_allocate()	

	def self.log_matches(results_ary)
		results_ary.each do |record|
			Solr::MATCH_LOG_FILE.write("id: " + record['id'].to_s + "\t" )
			Solr::MATCH_LOG_FILE.write("brand: " + record['brand'].to_s + "\t\t" )
			Solr::MATCH_LOG_FILE.write("series: " + record['series'].to_s + "\t\t\t\t" )
			Solr::MATCH_LOG_FILE.write("model: " + record['model'].to_s + "\t\t\t" )
			Solr::MATCH_LOG_FILE.write("kind: " + record['kind'].to_s + "\t\t" )
			Solr::MATCH_LOG_FILE.write("size: " + record['size'].to_s + "\t\t" )
			Solr::MATCH_LOG_FILE.write("score: " + record['score'].to_s + "\t\t" )
			Solr::MATCH_LOG_FILE.puts
		end
	end#self.log_matches

end # Retailer

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

after_action :set_access_control_headers
  def handle_options_request
    head(:ok) if request.request_method == "OPTIONS"
  end
  def set_access_control_headers
    headers['Access-Control-Allow-Origin'] = '*'
    headers['Access-Control-Allow-Methods'] = 'GET, POST, PUT, DELETE'
  end

  
end

app/controllers/makers_controller.rb
class MakersController < ApplicationController
	
  def index
  	@cymbals = Maker.all
  end

  def update
    maker = Maker.find(params[:id])
  	maker.retailers << Retailer.find(params[:r].to_i)
  	respond_to do |format| 
  		format.js
  		format.json
  	end #respond_to	
  end #update

  
  private 

  def makers_params
  params.require(:makers).permit(:id)	
  end# makers_params 	
end

app/controllers/retailers_controller.rb
class RetailersController < ApplicationController

	def allocate
		@rsp = Retailer.alloc(params[:merchant],params[:res],params[:rec])
	end #allocate

        def linktomaker
        p params[:id]
       Retailer.find(params[:id]).update(maker: Maker.find(params[:retailer][:maker_id]))
        p Retailer.find(params[:id])
        end
        def update 
         retailer = Retailer.find(params[:id])
        if params[:active] == "deactivate"
            retailer.update(active: false)
        elsif params[:active] == "activate"
            retailer.update(active: true)
        end
        
  	respond_to do |format| 
  		format.js
  		format.json
  	end #respond_to	
        end #update

  private
  def retailers_params
  params.require(:retailers).permit(:id)	
  end# makers_params 	
end #class RetailersController

app/controllers/searches_controller.rb
class SearchesController < ApplicationController

	def home
		render 'search'
	end	

	def search
		@makers = Solr.search(params[:q])[0]
		@retailers = []
		@makers.each() {|m| Maker.find(m).retailers.active.each() {|r| @retailers << r}}
    if @retailers.empty? 
    @no_result = true
    @retailers = Retailer.limit(100).order('RANDOM()').where.not(maker_id: 3604).where(active: true)
    end
		render 'results'
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/makers_helper.rb
module MakersHelper
end

app/helpers/retailers_helper.rb
module RetailersHelper


end

	

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-121872475-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-121872475-1');
</script>
    <title>Red Cymbal</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= stylesheet_link_tag    'resets','layout', media: 'all'%>
    <%= yield :css %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/retailers.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Fcymbals</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'retailer', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= yield :css %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/makers/index.html.erb
<p><h1>Makers#index</h1>
<p><p>Find me in app/views/makers/index.html.erb</p>

<%end %>

app/views/makers/show.html.erb
<h1><%=@maker.id %></h1>

app/views/retailers/allocate.html.erb
<% content_for :css do %>
<%= javascript_include_tag 'retailer' %>
 
<% end %>


<h1>  <%=params[:merchant] %>  </h1> <% @rsp.each do |r,makers| %>
	<header class="retailer">
		<h3><%=r.title %></h4>
		<p><%=r.id %></p>

		<% if r.active %>
                    <button class="deactivate" id=<%= "#{r.id}" %>>De-Activate</button>
		<% end %>	
		<%= form_for r , url: linkto_path(r.id),html: {class: "linktomaker"} do |f| %>
  <%= f.text_field :maker_id %>
  <%= f.submit "Allocate" %>
<% end %>
		<a href= <%=r.link %> target = 'blank'>Product Link</a>
	</header>
<div class="makers" id=<%= "#{r.id}" %>>
	<% if makers.empty? %>
			<h4>NO RESULT FOUND</h4>
		<% else %>
			<% makers.each do |m|  %>
				<div class="maker" >
					<ul>
						<% m.each do |k,v|  %>
							<li> <span class="key"><%= k %></span>	: <span class="val"> <%= v %></span>	</li>
						<% end %>
					</ul>
					<% if makers.index(m) == 0 && r.maker_id == makers[0]["id"].to_i %>
							<button class="remove" id=<%= "#{m['id']}" %>>Remove</button>
					<% else %>
					
							<button class="allocate" id=<%= "#{m['id']}" %>>Allocate</button> 
					<% end %>	
					
				</div>
			<% end %>	
		<% end %>
</div>

<% end %>



 

app/views/retailers/index.html.erb
<% @retailers.each do |r| %>

	


<h4 style="color: <%= "red" if r.maker.id == 3604 %>"><%=r.title %></h4>
<p><%=r.id %></p>
<a href= <%=r.link %> target = 'blank'>Product Link</a>
<ul>	
<li><%=r.maker.brand %></li>
<li><%=r.maker.code %></li>
<li><%=r.maker.series %></li>
<li><%=r.maker.model %></li>
<li><%=r.maker.kind %></li>
<li><%=r.maker.size %></li>
</ul>	
	
<% end %>

app/views/searches/results.html.erb
<% content_for :css do %>
 <%= stylesheet_link_tag 'svg','form','results', media: 'all'%>
 <%= javascript_include_tag 'searches' %>
 <meta name="Mediapartners-Google" content="index">
 <meta name="robots" content="noindex, nofollow">
<% end %>

<div id="wrapper">
	<%=render 'shared/left' %>
	<div id="container">
		<%=render 'shared/logo' %>
		<%= render 'shared/form' %>
		
		<!-- SEARCH RESULTS -->
		<main id="results">
			<div class="facets-container">

			</div>
			<div class="results-container">
				<% if @no_result%>
				<%= render partial: 'shared/noresult' %>	
				<% end %>
				<%= render partial: 'shared/result',  collection: @retailers %>

				
			</div><!-- Results Container -->
		</main>
		<!-- END SEARCH RESULTS -->
		</div>
	<%= render 'shared/right' %>
	
</div><!-- div#wrapper -->
<%= render 'shared/footer' %>

app/views/searches/search.html.erb
<% content_for :css do %>
 <%= stylesheet_link_tag    'svg','form','index' %>
 <%= javascript_include_tag 'searches' %>
 <% end %>

<div id="wrapper">
	<%=render 'shared/left' %>
	<div id="container">
		<%=  render 'shared/logo' %>
		<%= render 'shared/form' %>
	</div>
	<%= render 'shared/right' %>
	<%= render 'shared/footer' %>	
</div>

app/views/shared/_facet.html.erb
<a  href="" onclick="getFacets(this.dataset.ids)" data-ids= <%= "#{facet[1]}" %> ><li class="facet" data-ids= <%= "#{facet[1]}" %> > <span class="brand-name"><%=facet[0].capitalize%></span> </li></a>

app/views/shared/_footer.html.erb
<footer>
		<ul>
			<li><a href="about.html">About</a></li>
		</ul>
</footer>

app/views/shared/_form.html.erb
<div id="s-box">
			<form action="results" id="search-form">
				<input type="search"  name='q' value="find your sound.."><!--
				--><input id="search-button" type="submit" value="Go!">
			</form>
		</div>

app/views/shared/_left.html.erb
<div id="left-stripe" class="stripe">


</div>

app/views/shared/_logo.html.erb
<div id="logo" > 
<a href="/"><svg viewBox="0 0 260 40">
<text x="2" y="25"><tspan>C</tspan>ymbal <tspan>F</tspan>inder</text>
</svg></a>	
</div>

app/views/shared/_noresult.html.erb
<div id="no-result">

<h4>Your query returned no results...<h4>
<h4>But we will show you something anyway:)<h4>

</div>

app/views/shared/_result.html.erb
<div class="result googlify">
	<h1 class="result-header">
		<ul class="result-header-ul">
                        <% p result%>   
			<li class="merchant"> <%=result.merchant.name %> <span class="address"><%= result.merchant.state%></span></li>
			<li class="price"><span class="currency">AUD</span><%=result.price.to_i %></li>
		</ul>
	</h1>
	<div class="product-details">
		
		<div class="product-img-wrapper"> <img src="logo.png" alt="" class="product-img"> </div>
		  <p class="product-info"> <a href="<%=result.link %>" target="blank"><%=result.title %></a> </p> 
		
	</div>
</div>

app/views/shared/_right.html.erb
<div id="right-stripe" class="stripe">


</div>